"
" cooperr vimrc
"
" reference https://github.com/mhinz/vim-galore#minimal-vimrc

" two space tab
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" set line numbers
set number

" explicitly set 'nocompatible'
set nocompatible

" enable syntax highlighting
syntax on

" visualbell please
set vb

" temp files in same dir
"
" swap files
" // at end instructs vim to save directory path in filename
" set directory=$HOME/.vim/files/swap//
set noswapfile
"
" backup files
" set backup
" set backupdir=$HOME/.vim/files/backup/
" set backupext=-vimbackup
set nobackup
"
" undo files
" set undofile
" set undodir=$HOME/.vim/files/undo
set noundofile

set viminfo='100,n$HOME/.vim/files/info/viminfo

" show status line
set laststatus=2
" show ALL of last line
set display=lastline

" show current mode in command line
set showmode
" show already typed keys when more are expected
set showcmd

" faster redrawing
set ttyfast
" only redraw when necessary
set lazyredraw

